name: "EC2 Deploy via SSM"
description: "Create/reuse EC2 and run setup.sh with SSM (no SSH)"

inputs:
  region:         { required: true }
  ami-id:         { required: true }
  instance-type:  { required: true }
  tag-value:      { required: false, default: fruitstore-ec2 }
  script-path:    { required: false, default: scripts/setup.sh }
  iam-instance-profile: { required: false }

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with: { python-version: '3.12' }

    - run: pip install -r requirements.txt
      shell: bash

    - name: Run deploy via SSM
      shell: bash
      run: |
        python src/check_instance.py \
          --region "${{ inputs.region }}" \
          --ami-id "${{ inputs.ami-id }}" \
          --instance-type "${{ inputs.instance-type }}" \
          --tag-value "${{ inputs.tag-value }}" \
          --script-path "${{ inputs.script-path }}" \
          ${{ inputs.iam-instance-profile && format('--iam-instance-profile "{0}"', inputs.iam-instance-profile) || '' }}
