name: "EC2 Deploy Action"
description: "Check or create EC2 instance and run SSH script to start Flask server"

inputs:
  region:         { required: true }
  ami-id:         { required: true }
  instance-type:  { required: true }
  key-name:       { required: true }
  ssh-private-key: { required: true }
  ssh-public-key: { required: false }
  tag-value:      { required: false, default: fruitstore-ec2 }
  script-path:    { required: false, default: scripts/setup.sh }

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - run: pip install -r requirements.txt
      shell: bash

    # write keys; use printf to preserve exact content
    - name: Write SSH keys
      shell: bash
      run: |
        printf "%s" "${{ inputs.ssh-private-key }}" > fruitstore.pem
        chmod 400 fruitstore.pem
        if [ -n "${{ inputs.ssh-public-key }}" ]; then
          printf "%s" "${{ inputs.ssh-public-key }}" > fruitstore.pub
        fi

    - shell: bash
      run: |
        python src/check_instance.py \
          --region "${{ inputs.region }}" \
          --ami-id "${{ inputs.ami-id }}" \
          --instance-type "${{ inputs.instance-type }}" \
          --key-name "${{ inputs.key-name }}" \
          --tag-value "${{ inputs.tag-value }}" \
          --ssh-key-path fruitstore.pem \
          --public-key-path fruitstore.pub \
          --script-path "${{ inputs.script-path }}"
