name: Deploy

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS region"
        required: true
        default: "us-east-1"
      ami-id:
        description: "AMI ID"
        required: true
      instance-type:
        description: "EC2 instance type"
        required: true
        default: "t3.micro"
      key-name:
        description: "EC2 key pair name"
        required: true
      tag-value:
        description: "Tag value for idempotency"
        required: false
        default: "fruitstore-ec2"
      script-path:
        description: "Path to setup script"
        required: false
        default: "scripts/setup.sh"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::611771051034:role/GitHubOIDCDeployRole
          aws-region: ${{ github.event.inputs.region }}

      - name: Run custom EC2 deploy action
        uses: ./.github/actions/deploy
        with:
          region:        ${{ github.event.inputs.region }}
          ami-id:        ${{ github.event.inputs['ami-id'] }}
          instance-type: ${{ github.event.inputs['instance-type'] }}
          key-name:      ${{ github.event.inputs['key-name'] }}
          tag-value:     ${{ github.event.inputs['tag-value'] }}
          script-path:   ${{ github.event.inputs['script-path'] }}
          ssh-key:       ${{ secrets.EC2_SSH_KEY }}   # <-- pass secret here
